/**
 * Visual regression suite for the v1.3 Goal-centered shell.
 *
 * Linux baselines are generated by the update-visual-snapshots workflow.
 * These snapshots intentionally cover the new product surfaces rather than
 * the retired v1.2 module tabs.
 */
import { test, expect } from '@playwright/test'
import { installMocks, COMMON_WS_BOOTSTRAP } from './fixtures/setup.mjs'

test.describe('@visual v1.3 main surfaces', () => {
  test.beforeEach(async ({ context }) => {
    await installMocks(context, {
      messages: COMMON_WS_BOOTSTRAP,
      localStorage: { 'ia-color-scheme': 'vscode-light-plus' },
    })
  })

  test('Action Home', async ({ page }) => {
    await page.goto('/#/home')
    await expect(page.getByRole('heading', { name: '成竹', exact: true })).toBeVisible()
    await expect(page.getByRole('navigation', { name: '主导航' })).toBeVisible()
    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot('action-home.png', { fullPage: false, timeout: 30_000 })
  })

  test('Goal list', async ({ page }) => {
    await page.goto('/#/goals')
    await expect(page.getByRole('heading', { name: '求职目标', exact: true })).toBeVisible()
    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot('goals.png', { fullPage: false, timeout: 30_000 })
  })

  test('Person resume workspace', async ({ page }) => {
    await page.goto('/#/me/resume')
    await expect(page.getByRole('heading', { name: '我的成竹', exact: true })).toBeVisible()
    await expect(page.getByTestId('resume-mount-panel')).toBeVisible({ timeout: 8000 })
    await page.waitForTimeout(500)
    await expect(page).toHaveScreenshot('me-resume.png', { fullPage: false, timeout: 30_000 })
  })
})
